#!/bin/ksh
domainHome=$1
packageHome=$2
profileDirPath=${packageHome}/etc/profile.d
packageName=${packageHome##*/}
profilePath=${profileDirPath}/${packageName}.sh
mkdir -p ${profileDirPath}
Platform=`uname -s` ; [[ $Platform = Linux ]] && Platform=${Platform}-`uname -m`
cp ${packageHome}/.ssm.d/profile.sh ${profilePath}
echo "export SEQ_BIN=${packageHome}/bin" >> ${profilePath}
echo "export SEQ_MAESTRO_DOMAIN=${domainHome}" >> ${profilePath}
echo 'export TMPDIR=${TMPDIR:-/tmp/$USER/$$} && mkdir -p ${TMPDIR}' >> ${profilePath}
echo 'export TRUE_HOST=${TRUE_HOST:-$(hostname)}' >> ${profilePath}
chmod 644 ${profilePath}
